### PR TITLE
added tests for multiple tags

### LINKED ISSUE #57: Database multiple tags tests
Write tests for searching games with multiple tags. Right now we only have single tags being tested.

### PR DESCRIPTION
**Pull request by hagen-larsen-hl**
Resolves issue #57 added tests for multiple tags, also tests functionality of matchAll variable in GetGamesByTags.

### CODE REVIEW

**Review by kp-121 — APPROVED** [review]
The tests fail, which shows our get games by tags db function needs work. Good tests.

**Comment by hagen-larsen-hl** [comment]
@kp-121 When I try to run the tests, this is the error I get. Do you know what could be causing this?

Screen Shot 2022-08-07 at 6 17 24 PM

**Comment by kp-121** [comment]
> @kp-121 When I try to run the tests, this is the error I get. Do you know what could be causing this?
> 
> Screen Shot 2022-08-07 at 6 17 24 PM

I get this same error with the mock db. I can't figure out how to initialize the mock map. I only test with mongo and firestore.

**Comment by kp-121** [comment]
> The tests fail, which shows our get games by tags db function needs work. Good tests.

I'll create an issue to fix the get games by tags db function when you merge this.

**Comment by hagen-larsen-hl** [comment]
@kp-121  I get a similar error when testing with mongo

Screen Shot 2022-08-07 at 6 22 28 PM

**Comment by kp-121** [comment]
> @kp-121 I get a similar error when testing with mongo
> 
> Screen Shot 2022-08-07 at 6 22 28 PM

This looks like a db connection error, is your mongo container running?

**Comment by hagen-larsen-hl** [comment]
@kp-121 Its running from the docker-compose command, is there something else I'm supposed to do besides run `docker-compose up`?

**Comment by kp-121** [comment]
I just got the same error with mongo. It is running smooth with firestore though. I'm going to try to track this down.

Edit: The tests are running great.
@hagen-larsen-hl I forgot to start mongo db container and got the same error. I would double check with docker desktop that mongo db container is running.

**Comment by hagen-larsen-hl** [comment]
@kp-121 Where do I get the Firestore Project ID to test with Firestore?

**Comment by kp-121** [comment]
> @kp-121 Where do I get the Firestore Project ID to test with Firestore?

I had to create my own google cloud firestore and use that.

**Pull request merged**
